version: '3.3'
services:
    apiphyon:
        container_name: apipython
        ports:
            - '808:5000'
        image: 'apiphyon:v1.0'
        volumes:
            - ./:/data/
    web:
        image: 'php:apache'
        container_name: web
        ports :
            - '80:80'
        environment:
            - USERNAME=toto
            - PASSWORD=python
        volumes:
            - ./website:/var/www/html
        depends_on:
            - apiphyon